-- models/staging/stg_season_aggregates.sql
{{ config(materialized='view') }}

with src as (
  select *
  from {{ source('RAW', 'season_aggregates_data') }}
)

select
  cast(player_id as varchar) as player_id,
  cast(season as integer) as season,
  cast(season_type as varchar) as season_type,
  cast(completions as integer) as completions,
  cast(attempts as integer) as attempts,
  cast(passing_yards as integer) as passing_yards,
  cast(passing_tds as integer) as passing_tds,
  cast(interceptions as integer) as interceptions,
  cast(sacks as integer) as sacks,
  cast(sack_yards as integer) as sack_yards,
  cast(sack_fumbles as integer) as sack_fumbles,
  cast(sack_fumbles_lost as integer) as sack_fumbles_lost,
  cast(passing_air_yards as integer) as passing_air_yards,
  cast(passing_yards_after_catch as integer) as passing_yards_after_catch,
  cast(passing_first_downs as integer) as passing_first_downs,
  cast(passing_epa as float) as passing_epa,
  cast(passing_2pt_conversions as integer) as passing_2pt_conversions,
  cast(pacr as float) as pacr,
  cast(dakota as float) as dakota,
  cast(carries as integer) as carries,
  cast(rushing_yards as integer) as rushing_yards,
  cast(rushing_tds as integer) as rushing_tds,
  cast(rushing_fumbles as integer) as rushing_fumbles,
  cast(rushing_fumbles_lost as integer) as rushing_fumbles_lost,
  cast(rushing_first_downs as integer) as rushing_first_downs,
  cast(rushing_epa as float) as rushing_epa,
  cast(rushing_2pt_conversions as integer) as rushing_2pt_conversions,
  cast(receptions as integer) as receptions,
  cast(targets as integer) as targets,
  cast(receiving_yards as integer) as receiving_yards,
  cast(receiving_tds as integer) as receiving_tds,
  cast(receiving_fumbles as integer) as receiving_fumbles,
  cast(receiving_fumbles_lost as integer) as receiving_fumbles_lost,
  cast(receiving_air_yards as integer) as receiving_air_yards,
  cast(receiving_yards_after_catch as integer) as receiving_yards_after_catch,
  cast(receiving_first_downs as integer) as receiving_first_downs,
  cast(receiving_epa as float) as receiving_epa,
  cast(receiving_2pt_conversions as integer) as receiving_2pt_conversions,
  cast(racr as float) as racr,
  cast(target_share as float) as target_share,
  cast(air_yards_share as float) as air_yards_share,
  cast(wopr_x as float) as wopr_x,
  cast(special_teams_tds as integer) as special_teams_tds,
  cast(fantasy_points as float) as fantasy_points,
  cast(fantasy_points_ppr as float) as fantasy_points_ppr,
  cast(games as integer) as games,
  cast(tgt_sh as float) as target_share_alt,
  cast(ay_sh as float) as air_yards_share_alt,
  cast(yac_sh as float) as yac_share,
  cast(wopr_y as float) as wopr_y,
  cast(ry_sh as float) as rushing_yards_share,
  cast(rtd_sh as integer) as rushing_td_share,
  cast(rfd_sh as float) as rushing_first_down_share,
  cast(rtdfd_sh as float) as rushing_td_first_down_share,
  cast(dom as float) as dom,
  cast(w8dom as float) as w8dom,
  cast(yptmpa as float) as yptmpa,
  cast(ppr_sh as float) as ppr_share
from src

