{{ config(materialized='view') }}

with pbp_data as (
    select * from {{ source('RAW', 'pbp_data') }}
)

select
    play_id,
    game_id,
    old_game_id,
    home_team,
    away_team,
    season_type,
    week,
    posteam,
    posteam_type,
    defteam,
    side_of_field,
    yardline_100,
    game_date,
    quarter_seconds_remaining,
    half_seconds_remaining,
    game_seconds_remaining,
    game_half,
    CAST(quarter_end AS INTEGER)                          as quarter_end,
    CAST(drive AS INTEGER)                                as drive,
    sp,
    CAST(qtr AS INTEGER)                                  as qtr,
    CAST(down AS INTEGER)                                 as down,
    goal_to_go,
    TIME                                                  as play_time,
    yrdln,
    CAST(ydstogo AS INTEGER)                              as ydstogo,
    CAST(ydsnet AS INTEGER)                               as ydsnet,
    DESC                                                  as play_desc,
    play_type,
    CAST(yards_gained AS INTEGER)                         as yards_gained,
    CAST(shotgun AS INTEGER)                              as shotgun,
    CAST(no_huddle AS INTEGER)                            as no_huddle,
    CAST(qb_dropback AS INTEGER)                          as qb_dropback,
    CAST(qb_kneel AS INTEGER)                             as qb_kneel,
    CAST(qb_spike AS INTEGER)                             as qb_spike,
    CAST(qb_scramble AS INTEGER)                          as qb_scramble,
    pass_length,
    pass_location,
    CAST(air_yards AS INTEGER)                            as air_yards,
    CAST(yards_after_catch AS INTEGER)                    as yards_after_catch,
    run_location,
    run_gap,
    field_goal_result,
    CAST(kick_distance AS INTEGER)                        as kick_distance,
    extra_point_result,
    two_point_conv_result,
    home_timeouts_remaining,
    away_timeouts_remaining,
    CAST(timeout AS INTEGER)                              as timeout,
    timeout_team,
    td_team,
    td_player_name,
    td_player_id,
    CAST(posteam_timeouts_remaining AS INTEGER)           as posteam_timeouts_remaining,
    CAST(defteam_timeouts_remaining AS INTEGER)           as defteam_timeouts_remaining,
    CAST(total_home_score AS INTEGER)                     as total_home_score,
    CAST(total_away_score AS INTEGER)                     as total_away_score,
    CAST(posteam_score AS INTEGER)                        as posteam_score,
    CAST(defteam_score AS INTEGER)                        as defteam_score,
    CAST(score_differential AS INTEGER)                   as score_differential,
    CAST(posteam_score_post AS INTEGER)                   as posteam_score_post,
    CAST(defteam_score_post AS INTEGER)                   as defteam_score_post,
    CAST(score_differential_post AS INTEGER)              as score_differential_post,
    CAST(no_score_prob AS FLOAT)                          as no_score_prob,
    CAST(opp_fg_prob AS FLOAT)                            as opp_fg_prob,
    CAST(opp_safety_prob AS FLOAT)                        as opp_safety_prob,
    CAST(opp_td_prob AS FLOAT)                            as opp_td_prob,
    CAST(fg_prob AS FLOAT)                                as fg_prob,
    CAST(safety_prob AS FLOAT)                            as safety_prob,
    CAST(td_prob AS FLOAT)                                as td_prob,
    CAST(extra_point_prob AS FLOAT)                       as extra_point_prob,
    CAST(two_point_conversion_prob AS FLOAT)              as two_point_conversion_prob,
    CAST(ep AS FLOAT)                                     as ep,
    CAST(epa AS FLOAT)                                    as epa,
    CAST(total_home_epa AS FLOAT)                         as total_home_epa,
    CAST(total_away_epa AS FLOAT)                         as total_away_epa,
    CAST(total_home_rush_epa AS FLOAT)                    as total_home_rush_epa,
    CAST(total_away_rush_epa AS FLOAT)                    as total_away_rush_epa,
    CAST(total_home_pass_epa AS FLOAT)                    as total_home_pass_epa,
    CAST(total_away_pass_epa AS FLOAT)                    as total_away_pass_epa,
    CAST(air_epa AS FLOAT)                                as air_epa,
    CAST(yac_epa AS FLOAT)                                as yac_epa,
    CAST(comp_air_epa AS FLOAT)                           as comp_air_epa,
    CAST(comp_yac_epa AS FLOAT)                           as comp_yac_epa,
    CAST(total_home_comp_air_epa AS FLOAT)                as total_home_comp_air_epa,
    CAST(total_away_comp_air_epa AS FLOAT)                as total_away_comp_air_epa,
    CAST(total_home_comp_yac_epa AS FLOAT)                as total_home_comp_yac_epa,
    CAST(total_away_comp_yac_epa AS FLOAT)                as total_away_comp_yac_epa,
    CAST(total_home_raw_air_epa AS FLOAT)                 as total_home_raw_air_epa,
    CAST(total_away_raw_air_epa AS FLOAT)                 as total_away_raw_air_epa,
    CAST(total_home_raw_yac_epa AS FLOAT)                 as total_home_raw_yac_epa,
    CAST(total_away_raw_yac_epa AS FLOAT)                 as total_away_raw_yac_epa,
    CAST(wp AS FLOAT)                                     as wp,
    CAST(def_wp AS FLOAT)                                 as def_wp,
    CAST(home_wp AS FLOAT)                                as home_wp,
    CAST(away_wp AS FLOAT)                                as away_wp,
    CAST(wpa AS FLOAT)                                    as wpa,
    CAST(vegas_wpa AS FLOAT)                              as vegas_wpa,
    CAST(vegas_home_wpa AS FLOAT)                         as vegas_home_wpa,
    CAST(home_wp_post AS FLOAT)                           as home_wp_post,
    CAST(away_wp_post AS FLOAT)                           as away_wp_post,
    CAST(vegas_wp AS FLOAT)                               as vegas_wp,
    CAST(vegas_home_wp AS FLOAT)                          as vegas_home_wp,
    CAST(total_home_rush_wpa AS FLOAT)                    as total_home_rush_wpa,
    CAST(total_away_rush_wpa AS FLOAT)                    as total_away_rush_wpa,
    CAST(total_home_pass_wpa AS FLOAT)                    as total_home_pass_wpa,
    CAST(total_away_pass_wpa AS FLOAT)                    as total_away_pass_wpa,
    CAST(air_wpa AS FLOAT)                                as air_wpa,
    CAST(yac_wpa AS FLOAT)                                as yac_wpa,
    CAST(comp_air_wpa AS FLOAT)                           as comp_air_wpa,
    CAST(comp_yac_wpa AS FLOAT)                           as comp_yac_wpa,
    CAST(total_home_comp_air_wpa AS FLOAT)                as total_home_comp_air_wpa,
    CAST(total_away_comp_air_wpa AS FLOAT)                as total_away_comp_air_wpa,
    CAST(total_home_comp_yac_wpa AS FLOAT)                as total_home_comp_yac_wpa,
    CAST(total_away_comp_yac_wpa AS FLOAT)                as total_away_comp_yac_wpa,
    CAST(total_home_raw_air_wpa AS FLOAT)                 as total_home_raw_air_wpa,
    CAST(total_away_raw_air_wpa AS FLOAT)                 as total_away_raw_air_wpa,
    CAST(total_home_raw_yac_wpa AS FLOAT)                 as total_home_raw_yac_wpa,
    CAST(total_away_raw_yac_wpa AS FLOAT)                 as total_away_raw_yac_wpa,
    CAST(punt_blocked AS INTEGER)                          as punt_blocked,
    CAST(first_down_rush AS INTEGER)                       as first_down_rush,
    CAST(first_down_pass AS INTEGER)                       as first_down_pass,
    CAST(first_down_penalty AS INTEGER)                    as first_down_penalty,
    CAST(third_down_converted AS INTEGER)                  as third_down_converted,
    CAST(third_down_failed AS INTEGER)                     as third_down_failed,
    CAST(fourth_down_converted AS INTEGER)                 as fourth_down_converted,
    CAST(fourth_down_failed AS INTEGER)                    as fourth_down_failed,
    CAST(incomplete_pass AS INTEGER)                       as incomplete_pass,
    CAST(touchback AS INTEGER)                             as touchback,
    CAST(interception AS INTEGER)                          as interception,
    CAST(punt_inside_twenty AS INTEGER)                    as punt_inside_twenty,
    CAST(punt_in_endzone AS INTEGER)                       as punt_in_endzone,
    CAST(punt_out_of_bounds AS INTEGER)                    as punt_out_of_bounds,
    CAST(punt_downed AS INTEGER)                           as punt_downed,
    CAST(punt_fair_catch AS INTEGER)                       as punt_fair_catch,
    CAST(kickoff_inside_twenty AS INTEGER)                 as kickoff_inside_twenty,
    CAST(kickoff_in_endzone AS INTEGER)                    as kickoff_in_endzone,
    CAST(kickoff_out_of_bounds AS INTEGER)                 as kickoff_out_of_bounds,
    CAST(kickoff_downed AS INTEGER)                        as kickoff_downed,
    CAST(kickoff_fair_catch AS INTEGER)                    as kickoff_fair_catch,
    CAST(fumble_forced AS INTEGER)                         as fumble_forced,
    CAST(fumble_not_forced AS INTEGER)                     as fumble_not_forced,
    CAST(fumble_out_of_bounds AS INTEGER)                  as fumble_out_of_bounds,
    CAST(solo_tackle AS INTEGER)                           as solo_tackle,
    CAST(safety AS INTEGER)                                as safety,
    CAST(penalty AS INTEGER)                               as penalty,
    CAST(tackled_for_loss AS INTEGER)                      as tackled_for_loss,
    CAST(fumble_lost AS INTEGER)                           as fumble_lost,
    CAST(own_kickoff_recovery AS INTEGER)                  as own_kickoff_recovery,
    CAST(own_kickoff_recovery_td AS INTEGER)               as own_kickoff_recovery_td,
    CAST(qb_hit AS INTEGER)                                as qb_hit,
    CAST(rush_attempt AS INTEGER)                          as rush_attempt,
    CAST(pass_attempt AS INTEGER)                          as pass_attempt,
    CAST(sack AS INTEGER)                                  as sack,
    CAST(touchdown AS INTEGER)                             as touchdown,
    CAST(pass_touchdown AS INTEGER)                        as pass_touchdown,
    CAST(rush_touchdown AS INTEGER)                        as rush_touchdown,
    CAST(return_touchdown AS INTEGER)                      as return_touchdown,
    CAST(extra_point_attempt AS INTEGER)                   as extra_point_attempt,
    CAST(two_point_attempt AS INTEGER)                     as two_point_attempt,
    CAST(field_goal_attempt AS INTEGER)                    as field_goal_attempt,
    CAST(kickoff_attempt AS INTEGER)                       as kickoff_attempt,
    CAST(punt_attempt AS INTEGER)                          as punt_attempt,
    CAST(fumble AS INTEGER)                                as fumble,
    CAST(complete_pass AS INTEGER)                         as complete_pass,
    CAST(assist_tackle AS INTEGER)                         as assist_tackle,
    CAST(lateral_reception AS INTEGER)                     as lateral_reception,
    CAST(lateral_rush AS INTEGER)                          as lateral_rush,
    CAST(lateral_return AS INTEGER)                        as lateral_return,
    CAST(lateral_recovery AS INTEGER)                      as lateral_recovery,
    passer_player_id,
    passer_player_name,
    CAST(passing_yards AS INTEGER)                         as passing_yards,
    receiver_player_id,
    receiver_player_name,
    CAST(receiving_yards AS INTEGER)                       as receiving_yards,
    rusher_player_id,
    rusher_player_name,
    CAST(rushing_yards AS INTEGER)                         as rushing_yards,
    lateral_receiver_player_id,
    lateral_receiver_player_name,
    CAST(lateral_receiving_yards AS INTEGER)               as lateral_receiving_yards,
    lateral_rusher_player_id,
    lateral_rusher_player_name,
    CAST(lateral_rushing_yards AS INTEGER)                 as lateral_rushing_yards,
    lateral_sack_player_id,
    lateral_sack_player_name,
    interception_player_id,
    interception_player_name,
    lateral_interception_player_id,
    lateral_interception_player_name,
    punt_returner_player_id,
    punt_returner_player_name,
    lateral_punt_returner_player_id,
    lateral_punt_returner_player_name,
    kickoff_returner_player_name,
    kickoff_returner_player_id,
    lateral_kickoff_returner_player_id,
    lateral_kickoff_returner_player_name,
    punter_player_id,
    punter_player_name,
    kicker_player_name,
    kicker_player_id,
    own_kickoff_recovery_player_id,
    own_kickoff_recovery_player_name,
    blocked_player_id,
    blocked_player_name,
    tackle_for_loss_1_player_id,
    tackle_for_loss_1_player_name,
    tackle_for_loss_2_player_id,
    tackle_for_loss_2_player_name,
    qb_hit_1_player_id,
    qb_hit_1_player_name,
    qb_hit_2_player_id,
    qb_hit_2_player_name,
    forced_fumble_player_1_team,
    forced_fumble_player_1_player_id,
    forced_fumble_player_1_player_name,
    forced_fumble_player_2_team,
    forced_fumble_player_2_player_id,
    forced_fumble_player_2_player_name,
    solo_tackle_1_team,
    solo_tackle_2_team,
    solo_tackle_1_player_id,
    solo_tackle_2_player_id,
    solo_tackle_1_player_name,
    solo_tackle_2_player_name,
    assist_tackle_1_player_id,
    assist_tackle_1_player_name,
    assist_tackle_1_team,
    assist_tackle_2_player_id,
    assist_tackle_2_player_name,
    assist_tackle_2_team,
    assist_tackle_3_player_id,
    assist_tackle_3_player_name,
    assist_tackle_3_team,
    assist_tackle_4_player_id,
    assist_tackle_4_player_name,
    assist_tackle_4_team,
    CAST(tackle_with_assist AS INTEGER)                    as tackle_with_assist,
    tackle_with_assist_1_player_id,
    tackle_with_assist_1_player_name,
    tackle_with_assist_1_team,
    tackle_with_assist_2_player_id,
    tackle_with_assist_2_player_name,
    tackle_with_assist_2_team,
    pass_defense_1_player_id,
    pass_defense_1_player_name,
    pass_defense_2_player_id,
    pass_defense_2_player_name,
    fumbled_1_team,
    fumbled_1_player_id,
    fumbled_1_player_name,
    fumbled_2_player_id,
    fumbled_2_player_name,
    fumbled_2_team,
    fumble_recovery_1_team,
    CAST(fumble_recovery_1_yards AS INTEGER)               as fumble_recovery_1_yards,
    fumble_recovery_1_player_id,
    fumble_recovery_1_player_name,
    fumble_recovery_2_team,
    CAST(fumble_recovery_2_yards AS INTEGER)               as fumble_recovery_2_yards,
    fumble_recovery_2_player_id,
    fumble_recovery_2_player_name,
    sack_player_id,
    sack_player_name,
    half_sack_1_player_id,
    half_sack_1_player_name,
    half_sack_2_player_id,
    half_sack_2_player_name,
    return_team,
    CAST(return_yards AS INTEGER)                           as return_yards,
    penalty_team,
    penalty_player_id,
    penalty_player_name,
    CAST(penalty_yards AS INTEGER)                          as penalty_yards,
    replay_or_challenge,
    replay_or_challenge_result,
    penalty_type,
    CAST(defensive_two_point_attempt AS INTEGER)            as defensive_two_point_attempt,
    CAST(defensive_two_point_conv AS INTEGER)               as defensive_two_point_conv,
    CAST(defensive_extra_point_attempt AS INTEGER)          as defensive_extra_point_attempt,
    CAST(defensive_extra_point_conv AS INTEGER)             as defensive_extra_point_conv,
    safety_player_name,
    safety_player_id,
    season,
    CAST(cp AS FLOAT)                                       as cp,
    CAST(cpoe AS FLOAT)                                     as cpoe,
    CAST(series AS INTEGER)                                 as series,
    series_success,
    series_result,
    order_sequence,
    TRY_TO_TIMESTAMP_NTZ(start_time,  'MM/DD/YY, HH24:MI:SS')   as start_time_converted,
    TRY_TO_TIMESTAMP_NTZ(time_of_day, 'MM/DD/YY, HH24:MI:SS')   as time_of_day_converted,
    stadium,
    weather,
    nfl_api_id,
    play_clock,
    play_deleted,
    play_type_nfl,
    special_teams_play,
    st_play_type,
    end_clock_time,
    end_yard_line,
    CAST(fixed_drive AS INTEGER)                            as fixed_drive,
    fixed_drive_result,
    TRY_TO_TIMESTAMP_NTZ(drive_real_start_time, 'MM/DD/YY, HH24:MI:SS') as drive_real_start_time_converted,
    CAST(drive_play_count AS INTEGER)                       as drive_play_count,
    TRY_CAST(drive_time_of_possession AS TIME)              as drive_time_of_possession,
    CAST(drive_first_downs AS INTEGER)                      as drive_first_downs,
    CAST(drive_inside20 AS INTEGER)                         as drive_inside20,
    CAST(drive_ended_with_score AS INTEGER)                 as drive_ended_with_score,
    CAST(drive_quarter_start AS INTEGER)                    as drive_quarter_start,
    CAST(drive_quarter_end AS INTEGER)                      as drive_quarter_end,
    CAST(drive_yards_penalized AS INTEGER)                  as drive_yards_penalized,
    CAST(drive_start_transition AS INTEGER)                 as drive_start_transition,
    CAST(drive_end_transition AS INTEGER)                   as drive_end_transition,
    TRY_CAST(drive_game_clock_start AS TIME)                as drive_game_clock_start,
    TRY_CAST(drive_game_clock_end AS TIME)                  as drive_game_clock_end,
    drive_start_yard_line,
    drive_end_yard_line,
    drive_play_id_started,
    drive_play_id_ended,
    CAST(away_score AS INTEGER)                             as away_score,
    CAST(home_score AS INTEGER)                             as home_score,
    LOCATION                                                as game_location,
    RESULT                                                  as play_result,
    TOTAL                                                   as vegas_total,
    spread_line,
    total_line,
    div_game,
    roof,
    surface,
    temp,
    wind,
    home_coach,
    away_coach,
    stadium_id,
    game_stadium,
    aborted_play,
    success,

    PASS                                                      as is_pass,
    RUSH                                                      as is_rush,
    PLAY                                                      as is_play,
    SPECIAL                                                   as is_special,

    passer,
    passer_jersey_number,
    rusher,
    rusher_jersey_number,
    receiver,
    receiver_jersey_number,
    passer_id,
    rusher_id,
    receiver_id,
    NAME                                                      as player_name,
    jersey_number,
    ID                                                        as player_id,
    fantasy_player_name,
    fantasy_player_id,
    fantasy,
    fantasy_id,
    out_of_bounds,
    home_opening_kickoff,
    CAST(qb_epa AS FLOAT)                                   as qb_epa,
    CAST(xyac_epa AS FLOAT)                                 as xyac_epa,
    CAST(xyac_mean_yardage AS FLOAT)                        as xyac_mean_yardage,
    CAST(xyac_median_yardage AS FLOAT)                      as xyac_median_yardage,
    CAST(xyac_success AS FLOAT)                             as xyac_success,
    CAST(xyac_fd AS FLOAT)                                  as xyac_fd,
    CAST(xpass AS FLOAT)                                    as xpass,
    CAST(pass_oe AS FLOAT)                                  as pass_oe
from pbp_data